# Generated by Django 4.2.7 on 2024-01-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('y_of_exp', models.CharField(max_length=500)),
                ('no_of_happy_cus', models.CharField(max_length=500)),
                ('no_project_finished', models.CharField(max_length=500)),
                ('no_digital_awards', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('date_time', models.CharField(max_length=5000)),
                ('v_c', models.CharField(max_length=5000)),
                ('v_status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
